Updated scripts and added manual pages

diff --git a/bin/puffmatic-net b/bin/puffmatic-net
--- a/bin/puffmatic-net
+++ b/bin/puffmatic-net
@@ -4,18 +4,42 @@
 # for all hosts.
 #
 
-python3 -m puffmatic mirror --once
+VERBOSE=
+
+while getopts "hv" opt; do
+    case $opt in
+        h)
+            echo "$(basename $0) [-h] [-v]"
+	    exit 0
+	    ;;
+        v)
+            VERBOSE="--verbose"
+	    ;;
+        *)
+	    echo "invalid option"
+            exit 1
+	    ;;
+    esac
+done
+shift $((OPTIND-1))
+
+if [ ! -d hosts ]; then
+    echo No hosts directory found
+    exit 1
+fi
+
+python3 -m puffmatic ${VERBOSE} mirror --once
 
 for host in hosts/*; do
-     python3 -m puffmatic disklabel --host-dir="${host}"
+     python3 -m puffmatic ${VERBOSE} disklabel --host-dir="${host}"
 done
 
 for host in hosts/*; do
-    python3 -m puffmatic response --host-dir="${host}"
+    python3 -m puffmatic ${VERBOSE} response --host-dir="${host}"
 done
 
 for host in hosts/*; do
-    python3 -m puffmatic host-site-set --host-dir="${host}"
+    python3 -m puffmatic ${VERBOSE} host-site-set --host-dir="${host}"
 done
 
-python3 -m puffmatic site-set --site-dir=site
+python3 -m puffmatic ${VERBOSE} site-set --site-dir=site
diff --git a/bin/puffmatic-usb b/bin/puffmatic-usb
--- a/bin/puffmatic-usb
+++ b/bin/puffmatic-usb
@@ -4,19 +4,45 @@
 # suitable for installation from USB drive.
 #
 
+BIN=$0
 
-HOST_DIR="hosts/${1}"
+function help {
+    echo "$(basename $BIN) [-v] host"
+    exit 0
+}
+
+
+VERBOSE=
+
+while getopts "hv" opt; do
+    case $opt in
+        h)
+	    help
+	    ;;
+        v)
+            VERBOSE="--verbose"
+	    ;;
+        *)
+	    echo "invalid option"
+            exit 1
+	    ;;
+    esac
+done
+shift $((OPTIND-1))
 
 if [ -z "${1}" ]; then
-    echo "usage: $(basename $0) host"
+    help
     exit 1
 fi
 
-if [ ! -d ${HOST_DIR} ]; then
-    echo "no host dir ${HOST_DIR} for host ${1}"
+
+HOST_DIR="hosts/${1}"
+
+if [ ! -d "$HOST_DIR" ]; then
+    echo host directory $HOST_DIR not found
     exit 1
 fi
 
 set -e
-python3 -m puffmatic getimg --once
-python3 -m puffmatic patchimg --host-dir=${HOST_DIR}
+python3 -m puffmatic $VERBOSE getimg --once
+python3 -m puffmatic $VERBOSE patchimg --host-dir=${HOST_DIR}
